version: '3.9'

services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:password@mysql:3306/mydb"
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: